### ISSUE TITLE
Incorrect Boss KC

### ISSUE THREAD

**Issue by Axemen** [zedchance/blues_bot.py#22]
For some reason Boss KC is getting mixed up when generating the KC table. 

![338f849cae02a43709a67110efa2a27d](https://user-images.githubusercontent.com/10989702/107129908-70ad9180-688e-11eb-953b-add3ae1e64c4.png)

If there's anything other information you need or just some help fixing it then let me know. From the looks of it it seems that for whatever reason the site that you're pulling the boss KC from has changed they're HTML making the parsing of it off.

**Comment by Axemen** [comment]
After viewing the code it looks like in the hiscores.py file when assigning the KC to the class's variables the number is off by one https://github.com/zedchance/blues_bot.py/blob/8b447d8cd4ee4b12203d2c628b89790495303d33/helpers/hiscore.py#L161

The numbers go from 33 to 35. causing it to skip the Sire KC which should be 34. 

I'm not sure what's happening to the zulrah KC as it should be throwing an error when trying to assign it.

**Comment by Axemen** [comment]
Upon further review/investigation it appears that the issue started after the bot went down on January 9th/10th. So it's probably not an issue stemming from a change in the response from the hiscores.

**Comment by Axemen** [comment]
after cloning/forking I was able to find out that Sire is now 36 in the response instead of 35. Something must have been added beforehand but I have no idea what.

**Comment by Axemen** [comment]
So I have now noticed that the Minigame scores are incorrect as well with LMS and Bounty Hunter being off. It appears that LMS has been moved to the 35th position causing the error with the boss KC and the 24th position being turned into something unknown. it's current values are [-1, -1] for every thing I've tried. Also the Bounty Hunter scores have been moved to the 25th, and 26th position.

**Comment by Axemen** [comment]
In review it appears that the 24th index has been changed to something unknown.

The 34th index has been changed to LMS and all the boss KC have been pushed up one number as a result. 

The clue positions have not changed for some reason. 

The 35th index is currently unknown as well as every value i've seen is currently [-1, -1]

**Comment by Axemen** [comment]
Link to PR fixing the Hi-scores issues on the bot. However this does not fix the differences when using the `!b xp` command as it uses CrystalMethLabs to get the difference which is out of control of the bot. 

https://github.com/zedchance/blues_bot.py/pull/23

**Comment by zedchance** [comment]
Hey! Thanks for submitting the issue, I was in the middle of writing a response when my power just went out!

You're definitely right, there is a problem with the parsing of the hiscore API! And you're right, CML is also experiencing the same problem. 

Once my power comes back on I will review your PR!
